# Generated by Django 5.0.14 on 2025-11-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_convert_images_to_binary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uicevent",
            name="image",
        ),
    ]
