# Generated by Django 5.2.7 on 2025-10-23 01:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("accuracy", models.FloatField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_round",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.gameround",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leaderboard Entries",
                "ordering": ["-score", "-accuracy"],
                "indexes": [
                    models.Index(
                        fields=["-score"], name="leaderboard_score_c577fc_idx"
                    ),
                    models.Index(fields=["date"], name="leaderboard_date_76536f_idx"),
                ],
            },
        ),
    ]
